library("limma")
library("Glimma")
library("edgeR")
library("pathview")
library("gage")
library("gageData")
library("KEGGREST")
library("Rsubread")
library("biomaRt")
library("RColorBrewer")
library("gplots")
library("FGNet")
library("BSgenome.Celegans.UCSC.ce11")
library("AnnotationDbi")
library("CoRegNet")

